site_name: Dash
extra_css: [extra.css]
theme:
  name: material
  palette:
    primary: blue
repo_url: https://github.rbx.com/hcollins/Dash

nav:
  - Home: index.md
  - API Reference: api.md
  - Types: types.md
  - Tags: tags.md
