site_name: Dash
extra_css: [extra.css]
theme:
  name: material
  palette:
    scheme: slate
    primary: blue

nav:
  - Home: index.md
  - Classes: classes.md
  - Functions: functions.md
  - Symbols: symbols.md
  - Types: types.md
