local Packages = game:GetService("ReplicatedStorage").Packages
local JestGlobals = require(Packages.Dev.JestGlobals)
local describe = JestGlobals.describe
local it = JestGlobals.it
local expect = JestGlobals.expect

local Dash = require(Packages.Dash)
local frequencies = Dash.frequencies

describe("frequencies", function()
	it("without handler should count encounters of all values", function()
		local input = { "Red", "Black", "Orange", "Red" }
		local output = frequencies(input)
		expect(output).toEqual({ ["Black"] = 1, ["Orange"] = 1, ["Red"] = 2 })
	end)

	it("should count elements by keys generated by handler", function()
		local function toNeutral(color)
			return if Dash.includes({ "Black", "Gray", "White" }, color) then "Neutral" else "Non-neutral"
		end

		local output = Dash.frequencies({ "Black", "Orange", "Blue", "Gray", "White" }, function(color)
			return toNeutral(color)
		end)
		expect(output).toEqual({ ["Neutral"] = 3, ["Non-neutral"] = 2 })
	end)
end)
